DTSPO-172 Create module to reference common tags
hmcts/terraform-module-common-tags pull request #1
Opened 2021-03-31 07:33 UTC by mokainos

https://tools.hmcts.net/jira/browse/DTSPO-172

2021-03-31 12:51 UTC, timja commented on variables.tf
> +}
```suggestion
}

```

2021-03-31 12:52 UTC, timja commented on main.tf
> +    staging     = ["ldata", "stg", "aat"]
```suggestion
    staging     = ["ldata", "stg", "aat", "nle"]
```

2021-03-31 13:12 UTC, timja requested changes
README needs re-generating, output is wrong and so is description

2021-03-31 13:20 UTC, mokainos commented
> README needs re-generating, output is wrong and so is description

updated the file

2021-03-31 13:24 UTC, timja commented on README.md
> +
```suggestion
```

2021-03-31 13:24 UTC, timja commented on README.md
> +# Terraform module to reference common tags.
a heading is not a sentence
```suggestion
# Terraform module to reference common tags
```

2021-03-31 13:24 UTC, timja commented on README.md
> +## Tagging policy documentation.
```suggestion
## Tagging policy documentation
```

2021-03-31 13:24 UTC, timja commented on main.tf
> +    businessArea = var.businessArea
can we validate this is one of the allowed values?

2021-03-31 14:37 UTC, timja requested changes

2021-03-31 14:37 UTC, timja commented on variables.tf
> +    condition = can(regex("^CFT|^Crime|^Cross-Cutting", var.businessArea))
as discussed this should be moved to configuration (yml file) rather than an input

2021-03-31 14:37 UTC, timja commented on variables.tf
> +    condition = can(regex("^probate|^divorce|^core", var.application))
as discussed this should be moved to configuration (yml file) rather than an input

2021-04-01 12:20 UTC, timja commented on team-config.yml
> +    application: "core"
application and business area should be explained somehow, maybe a comment at the top of the file saying businessArea must be one of ...

and that application is normally the team name except for 'platform' which is core

2021-04-01 13:00 UTC, timja approved these changes

2021-04-01 13:25 UTC, merged